#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias edit="emacsclient -n"
alias gco="noglob git checkout"

# maven aliases
alias mci="mvn clean install"

ps | grep "ssh-agent" > /dev/null
if [[ $? -ne 0 ]] ; then
    eval $(ssh-agent -s)
    ssh-add ~/.ssh/private-id_rsa
fi

