#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export TERM=xterm-256color

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias edit="emacsclient -n"
alias gco="noglob git checkout"
alias gll="gl -6"
alias ll="ls -lha"
alias mux=tmuxinator

# maven aliases
alias mci="mvn clean install"


